CREATE TABLE IF NOT EXISTS PLAYERS (
    "_id" SERIAL PRIMARY KEY,
    "playerName" TEXT UNIQUE NOT NULL,
    "password" TEXT NOT NULL,
    "ELO" INTEGER DEFAULT 1000,
    "gamesPlayed" INTEGER DEFAULT 0,
    "gamesWon" INTEGER DEFAULT 0,
    "XP" INTEGER DEFAULT 0,
    "level" INTEGER DEFAULT 1,
    "created_at" TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS GAMES (
    "_id" SERIAL PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS PLAYER_GAMES (
    "_id" SERIAL PRIMARY KEY,
    "playerId" INTEGER REFERENCES PLAYERS("_id") NOT NULL,
    "gameId" INTEGER REFERENCES GAMES("_id") NOT NULL,
    "ELOGained" INTEGER NOT NULL,
    "XPGained" INTEGER NOT NULL,
    "position" INTEGER CHECK ("position" >= 1) NOT NULL
);

CREATE TABLE IF NOT EXISTS LOGS (
    "_id" SERIAL PRIMARY KEY,
    "gameId" INTEGER REFERENCES GAMES("_id") NOT NULL,
    "log" TEXT NOT NULL,
    "created_at" TIMESTAMP DEFAULT NOW()
);